### ISSUE TITLE
Can not Build Docker Image!

### ISSUE THREAD

**Issue by hosseinsmart** [strukturag/docker-webrtc-turnserver#2]
hi
when i try to run this command "docker build -t docker-webrtc-turnserver" the error below is apear:
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

**Comment by longsleep** [comment]
You are missing the final dot in the command

`docker build -t docker-webrtc-turnserver .`  <<< NOTE the single dot at the end.

**Comment by hosseinsmart** [comment]
thanks.
