### ISSUE TITLE
Image Not Run!

### ISSUE THREAD

**Issue by hosseinsmart** [strukturag/docker-webrtc-turnserver#4]
hi
when i want to run the docker image with this code:
docker run --rm --net=host --name my-spreed-turnserver -i -v `pwd`/data:/srv -t spreed-turnserver
this message apear:
Unable to find image 'spreed-turnserver:latest' locally
Pulling repository docker.io/library/spreed-turnserver
docker: Error: image library/spreed-turnserver:latest not found.
See 'docker run --help'.

**Comment by longsleep** [comment]
Please follow the instructions. You probably have forgot to build the docker image. https://github.com/strukturag/docker-webrtc-turnserver#build-docker-image

Note that we also provide official builds at https://hub.docker.com/r/spreed/turnserver/

**Comment by longsleep** [comment]
Ah i see now, maybe the docs are wrong? If you built the image try to use the same `-t` parameter value for both commands. The docs seem to use different ones. Will fix that on monday. Thanks!

**Comment by hosseinsmart** [comment]
i built the image but can not run it!

**Comment by hosseinsmart** [comment]
i fixed it, you could write "docker-webrtc-turnserver" instead "spreed-turnserver" in run command.
